### ISSUE TITLE
Bootstrap failed...`The ID value is not specified. Parameter Name: id'.

### ISSUE THREAD

**Issue by kusokuso1** [and0p/NesVoxel#6]
@toolboc
Hello, Paul. A co-worker of mine in Japan is running into an error when attempting to build and deploy the hololensopt branch from https://github.com/toolboc/NesVoxel.

Error:
DEP6701 : 予期しないエラーが発生したため、ブートストラップに失敗しまし
た: 'The ID value is not specified.
パラメーター名:id'。

(Rough translation)
DEP6701: Bootstrap failed due to an unexpected error. 'The ID value is
not specified.
Parameter Name: id'.

He said he followed the instructions.

Do you have any hints for me to relay to him to get this thing running? Fwiw, it runs nice-like on hololens emulator. Thanks in advance!

**Comment by and0p** [comment]
I'd give this a shot:

http://stackoverflow.com/questions/38077847/out-of-process-server-in-voip

They mention these steps:

"Right Click the project --> Properties --> Manifest Tool --> General.
Fill the field "Assembly Identity" with any number. After that compiles, run and works like a charm."

**Comment by kusokuso1** [comment]
@and0p 
Thanks for the help, kind sir.  I've relayed this info to the concerned party.  Will update with the results.

**Comment by toolboc** [comment]
@kusokuso1 , I've seen this before.  It usually indicates that device and dev environment are not synced.  The fact that this works in the emulator but not on the device supports this theory.  Ensure that your hololens device is updated to latest update in settings.  Also, ensure that Visual Studio and Windows 10 itself are updated to latest on the dev machine.

**Comment by kusokuso1** [comment]
Hey, thanks a lot for the help guys. 
@and0p
So the programmer here (Mr. Nakane) tried setting the Assembly Identity parameter, but that didn't seem to fix it (produced the same error).

@toolboc
For some reason, apparently we can't download apps from the Windows store says "Try again later.  Something happened on your end." Seems this issue crept up some time after we started deploying to remote machine (hololens) via VS.  

Maybe that's a sign that hololens isn't getting the "real" latest updates?  Last I checked Windows 10 updates are set to automatically update (on both hololens and dev machine).  VS 2015 version is currently 4.6.2.  Regardless, once I can get a hold of the PC, I'll double-check that the 3 things you mentioned are updated to latest.  If we can't update, I'd suspect the proxy server is the culprit.  It wouldn't be the first time.

Thanks!

Note:  
Mr. Nakane finds it strange that C# projects work fine but C++ ones don't.  He was able to successfully complete all the hololens academy tutorials.  Fwiw, we're both new to hololens (seeing that it officially arrived in Japan a few weeks ago).

There is only one Windows 10 (dev) PC in the company, and it's got 2 accounts on it.   1 mine, the other his.  

Edit: Fixed the downloading issues.  The company's network proxy settings needed some finagling.

**Comment by toolboc** [comment]
Just checked out over here and was able to reproduce.  I will let you know what I find.

edit: Found it!

**Comment by toolboc** [comment]
You need to ensure that a value (ip address) is set for "Machine Name" in both the Release and Debug configuration (Right-Click NS3Hololense Project => Properties => Debugging):
![image](https://cloud.githubusercontent.com/assets/2018336/23023753/9920ee22-f41c-11e6-96f8-968ceb1ee455.png)

Worked perfect on my device over here!

**Comment by kusokuso1** [comment]
@toolboc 
Thanks for the speedy assistance (and ss!).  Will let you know of the results within a few hours.

Edit: It worked.  Thanks a ton.  Now we just have to figure out how to get this Xbox One controller paired to the hololens.
