### ISSUE TITLE
Setting up an Xbox One S controller

### ISSUE THREAD

**Issue by kusokuso1** [and0p/NesVoxel#7]
@toolboc 
I'm pretty sure this Xbox One controller we have is an S; it's got bluetooth capability, and uses 2 AA batteries.  

We've never paired it to a PC before though.  There are 2 devices appearing/disappearing in the bluetooth device list.  No device with the name Xbox Controller or even controller. 

I looked around for some simple instructions on setting up this controller on ahololens but couldn't find any clear, recent info on it.  

We suspect the reason why it's not showing up in the list with a proper name is because it's not updated to the latest firmware. It's just a guess, because we don't know how to verify the current firmware on it, and we don't know the necessary/required firmware.  

Unfortunately, considering it's been lent to us by a publisher for development on a different, non-Hololens-related project, even if we did want to update the firmware we probably shouldn't.

Do you by any chance have any tips on setting it up that doesn't require a firmware update?

**Comment by toolboc** [comment]
If I recall correctly, a controller firmware update is **required** for pairing to the HoloLens.  I understand your concern of not wanting to modify the controller, but it is harmless and required for proper operation for any device that it is connected to (HoloLens, Xbox, PC). 

You can update the device on a Windows 10 PC using by following the **Update via PC** instructions @ http://support.xbox.com/en-US/xbox-one/accessories/update-controller-for-stereo-headset-adapter

We should probably direct future NesVoxel HoloLens related issues to my HoloLens Optimized fork.

**Comment by kusokuso1** [comment]
@toolboc 
Thanks again for the help! Apologies for posting this here.  I couldn't find an issues panel on the hololens optimized fork located here https://github.com/toolboc/NesVoxel.

Edit: We successfully updated the controller firmware. Looks like the Xbox controllers we have here (3 company owned, 8 lent) aren't the S type.  (Just came across[ a way to distinguish those that support bluetooth](https://support.xbox.com/en-US/xbox-on-windows/accessories/connect-and-troubleshoot-xbox-one-bluetooth-issues-windows-10) from those that don't, and found ours falls into the latter category.)

**Comment by kusokuso1** [comment]
**This is different from the orig title** 
I was wondering if you might have any plans to get this to work with other bluetooth devices. We have a bluetooth keyboard, and, dare I say it, a PS4 controller.

**Comment by toolboc** [comment]
@kusokuso1 

Per the changeset which includes "Xbox One S controller support"
https://github.com/toolboc/NesVoxel/commit/053e4da12360cdc02402920bff2f0f14ae70893e

It should be possible to configure for a variety of different inputs and may actually work out the box with other controllers.  

I do not have plans to test or extend to other devices at this time.

BTW, "Issues" have been enabled on my fork.

**Comment by kusokuso1** [comment]
@toolboc 
Got it, thanks for the info.  It's extremely appreciated.  

Any further hololens-related issues I will post on the new Issues page.
